formatter: markdown table
output:
  file: README.md
  mode: inject
  output-template: |
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
  sections:
    show: [inputs, outputs, providers, requirements, resources]
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: false
  indent: 2
  lockfile: false
  required: true
  sensitive: true
  type: true